# Generated by Django 3.2.16 on 2022-12-22 07:52

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0004_notificationmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
    ]
