# Generated by Django 4.1.4 on 2022-12-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0006_vehicle_reservation_expire_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='reservation_expire_time',
        ),
    ]
