# Generated by Django 4.1.4 on 2022-12-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0007_remove_vehicle_reservation_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_carbon_saved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carbon saved in grams'),
        ),
        migrations.AlterField(
            model_name='ridetable',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
