# Generated by Django 4.1.4 on 2022-12-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0008_user_total_carbon_saved_alter_ridetable_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridetable',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetable',
            name='pause_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetable',
            name='resume_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetable',
            name='total_pause_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ridetable',
            name='total_running_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
