# Generated by Django 4.1.4 on 2022-12-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0009_alter_ridetable_end_date_alter_ridetable_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Kilometer travelled'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_carbon_saved',
            field=models.FloatField(blank=True, null=True, verbose_name='Carbon saved in grams'),
        ),
    ]
