# Generated by Django 4.1.4 on 2022-12-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0012_alter_user_total_carbon_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='per_min_charge',
            field=models.CharField(default='2.5', max_length=10, verbose_name='Per Minute Running Charge'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='per_pause_charge',
            field=models.CharField(default='0.5', max_length=10, verbose_name='Per Minute Pause Charge'),
        ),
    ]
