# Generated by Django 4.1.4 on 2022-12-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0013_alter_vehicle_per_min_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentaccount',
            name='account_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
