# Generated by Django 4.1.4 on 2023-01-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0014_alter_userpaymentaccount_account_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celery running task id'),
        ),
    ]
