# Generated by Django 4.1.4 on 2023-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0017_alter_ridetable_total_pause_resume_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridetable',
            name='total_pause_resume_time',
        ),
        migrations.AlterField(
            model_name='ridetimehistory',
            name='pause_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetimehistory',
            name='resume_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridetimehistory',
            name='total_pause_resume_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
