# Generated by Django 4.1.4 on 2023-01-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0018_remove_ridetable_total_pause_resume_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridetimehistory',
            old_name='total_pause_resume_time',
            new_name='one_pause_time',
        ),
        migrations.RemoveField(
            model_name='ridetable',
            name='pause_time',
        ),
        migrations.RemoveField(
            model_name='ridetable',
            name='resume_time',
        ),
    ]
