# Generated by Django 4.1.4 on 2023-01-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0019_rename_total_pause_resume_time_ridetimehistory_one_pause_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridetimehistory',
            old_name='one_pause_time',
            new_name='pause_duration',
        ),
    ]
