# Generated by Django 4.1.4 on 2023-01-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0022_alter_ridetimehistory_pause_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50, verbose_name='Station Name')),
                ('address', models.TextField(verbose_name='Station address')),
                ('area', models.CharField(max_length=50, verbose_name='Area of station')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitude of Station')),
                ('long', models.CharField(max_length=50, verbose_name='Longitude of station')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elekgo_app.station', verbose_name='Vehicle Station'),
        ),
    ]
