# Generated by Django 4.1.4 on 2023-01-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0023_station_vehicle_vehicle_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='elekgo_app.station', verbose_name='Vehicle Station'),
            preserve_default=False,
        ),
    ]
