# Generated by Django 4.1.4 on 2023-01-09 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0025_user_avg_speed_user_driving_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station_object', to='elekgo_app.station', verbose_name='Vehicle Station'),
        ),
    ]
