# Generated by Django 4.1.4 on 2023-01-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0027_alter_vehicle_vehicle_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='long',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
    ]
