# Generated by Django 4.1.4 on 2023-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0029_alter_vehicle_battery_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='total_km_capacity',
            field=models.CharField(default='25', max_length=20),
        ),
    ]
