# Generated by Django 4.1.4 on 2023-01-09 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0030_alter_vehicle_total_km_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Voucher Number')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Is voucher Used')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Voucher used by user')),
            ],
        ),
    ]
