# Generated by Django 4.1.4 on 2023-01-09 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0031_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Voucher Number'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Voucher used by user'),
        ),
    ]
