# Generated by Django 4.1.4 on 2023-01-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0032_alter_voucher_code_alter_voucher_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Voucher Code'),
        ),
    ]
