# Generated by Django 4.1.4 on 2023-01-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0033_alter_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
