# Generated by Django 4.1.4 on 2023-01-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0035_alter_voucher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridetable',
            name='gst_cost',
            field=models.FloatField(default=10, verbose_name='GST applied'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridetable',
            name='pause_cost',
            field=models.FloatField(default=20, verbose_name='Pause cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridetable',
            name='ride_km',
            field=models.FloatField(default=12.5, verbose_name='Ride distance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridetable',
            name='running_cost',
            field=models.FloatField(default=150.1, verbose_name='Running cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridetable',
            name='total_cost',
            field=models.FloatField(default=154.2, verbose_name='Total cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridetable',
            name='total_cost_with_gst',
            field=models.FloatField(default=160.23, verbose_name='Total cost with GST'),
            preserve_default=False,
        ),
    ]
