# Generated by Django 4.1.4 on 2023-01-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0037_alter_ridetable_gst_cost_alter_ridetable_pause_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentaccount',
            name='account_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
