# Generated by Django 4.1.4 on 2023-01-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0038_alter_userpaymentaccount_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridetable',
            name='total_pause_time',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='ridetable',
            name='total_running_time',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
