# Generated by Django 4.1.4 on 2023-01-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0040_alter_ridetable_total_pause_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridetable',
            name='total_pause_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ridetable',
            name='total_running_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
