# Generated by Django 4.1.4 on 2023-01-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0041_alter_ridetable_total_pause_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridetable',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='elekgo_app.vehicle'),
        ),
    ]
