# Generated by Django 4.1.4 on 2023-01-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0043_alter_ridetable_riding_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_version', models.CharField(max_length=50, verbose_name='Android Version')),
                ('ios_version', models.CharField(max_length=50, verbose_name='IOS Version')),
                ('is_android_force_update', models.BooleanField(verbose_name='Android force update')),
                ('is_ios_force_update', models.BooleanField(verbose_name='IOS force update')),
                ('android_updated_url', models.CharField(max_length=50, verbose_name='Android updated url')),
                ('ios_updated_url', models.CharField(max_length=50, verbose_name='IOS updated url')),
            ],
        ),
    ]
