# Generated by Django 4.1.4 on 2023-01-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0044_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Change description'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Change title'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='android_updated_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Android updated url'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='android_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Android Version'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='ios_updated_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IOS updated url'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='ios_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IOS Version'),
        ),
    ]
