# Generated by Django 4.1.4 on 2023-02-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0046_user_is_referral_code_used_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rf_used_count',
            field=models.IntegerField(default=0),
        ),
    ]
