# Generated by Django 4.1.4 on 2023-02-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0047_user_rf_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='phone',
            field=models.CharField(default=1, max_length=12, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
