# Generated by Django 4.1.4 on 2023-02-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0049_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='is_cashfree_payment',
            field=models.BooleanField(default=True, verbose_name='Is Cashfree Payment?'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
