# Generated by Django 4.1.4 on 2023-03-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0050_paymentmodel_is_cashfree_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridetable',
            name='last_pause_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Last Pause Time'),
        ),
        migrations.AddField(
            model_name='ridetable',
            name='last_resume_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Last Resume Time'),
        ),
    ]
