# Generated by Django 4.1.4 on 2023-03-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elekgo_app', '0052_alter_voucher_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
    ]
